### ISSUE TITLE
Remove sleep from Travis

### ISSUE THREAD

**Issue by kenan-rhoton** [doner-kebard/card-game-backend#13]
**Description of the current situation**
Currently there's a sleep command to make the travis build pass by making it wait between launching the ring server and launching the pact verification.

**Description of the wanted situation**
There should be a better approach to this. We should ensure somehow that the server is running whenever we launch the pact verification

**Considered alternatives**
One option is simply to launch the server at the very beginning and hope it's up by the time the verification comes around (which it probably will be, realistically).

Ideally, though, the pact verification would as part of the process first launch and then shutdown the server.

**Comment by Masclins** [comment]
It seemed to me that this could be solved through this: https://blog.theodo.fr/2017/08/serverless-applications-aws-travis-make-deployment-great/

If we properly simulate the backend running on AWS, we'll probably be able to change this, test our code better and remove any need from this sleep.

**Comment by Masclins** [comment]
I think this is no longer needed thanks to #21, since we no longer need pacts, do we?

**Comment by kenan-rhoton** [comment]
completely true, closing
