### ISSUE TITLE
Remove irrelevant branches

### ISSUE THREAD

**Issue by Masclins** [doner-kebard/card-game-backend#15]
**Description of the current situation**
We have many branches to this project, while none has anything to do with the backend.

**Description of the wanted situation**
Having all those branches closed.

**Considered alternatives**
Maybe they should be copied on another project, but I think they are already been worked on, not taking this into account.

**Additional context**
I didn't want to close them myself in case someone needs them here for some weird reason.

**Comment by Masclins** [comment]
To make sure no work is lost, I think the last one working on each one should be the one closing it.

@kenan-rhoton could you check if we need `aws-lambda`?
@pernilsalat could you check if we need  `front-adapt` or `with-css-and-sass`?

**Comment by kenan-rhoton** [comment]
aws-lambda was to put the proejct up in amazon... this might be unnecessary and overkill, maybe we could just get an OVH server to start?

**Comment by Masclins** [comment]
I'm completely against working with OVH. I had an awful experience regarding their customer support.

**Comment by kenan-rhoton** [comment]
Good to know, but we can look at other options :upside_down_face:
