### ISSUE TITLE
PlayerID not checked when retrieving a game

### ISSUE THREAD

**Issue by kenan-rhoton** [doner-kebard/card-game-backend#20]
**Description**
When requesting a game, the system does not validate that your player-id is one of the players allowed to view it, it simply gives you the game anyway.

**To Reproduce**
Steps to reproduce the behavior (with `httpie`):
1. `http POST :3000/lobby` -> assume the ID returned is `0 
2. `http GET :3000/games/0/player/ICanWriteAnythingHereAndItDoesntMatter`
3. Obtain game info just as if you were the game owner.

**Expected behavior**
You should get a 404 or 403 or something, giving you no info on the game without a valid ID

**Comment by Masclins** [comment]
I don't 100% agree on that.
Letting players see games that are not theirs means that we can easily create an spectator mode, which I think's really interesting. Also it could let different apps access the API and gather game data without needing the player id's (and I think that's fine if it's an open game).

**Comment by kenan-rhoton** [comment]
In particular, this allows a player to see the other player's hand and current play, so that's a problem :upside_down_face: 

Also, I think it's just completely screwed up and doesn't allow for a correct game to be played at all, but it's hard to tell until we get some real outside tests (and I'm starting to think we should dump Pact, it's too convoluted for what we want, really)

**Comment by Masclins** [comment]
I tried the steps on "**To Reproduce**" and I get a game were all cards as shown as opponent's, so I see no player's hand.

Still, we should add a playerId check, to show a spectator view (or no view at all) when appropiate, but I simply don't think it's that important.

**Comment by kenan-rhoton** [comment]
I think it's still undesirable because we didn't define this behavior, so it's a bug until we at least know why exactly it's happening...
