### ISSUE TITLE
Cards with multiple abilities

### ISSUE THREAD

**Issue by Masclins** [doner-kebard/card-game-backend#26]
**Description of the current situation**
Cards can only have a single ability, which are *row-affinity*, *strengthen* and *weaken*.

**Description of the wanted situation**
Cards should be able to have multiple abilities and require multiple targets.

**Considered alternatives**
We could leave it right it is, and create a new ability for the combination of two of them (such as *row-affinity-and-weaken*). This wouldn't solve cases where we'd like two different targets.

**Comment by kenan-rhoton** [comment]
I would not take the "create a new ability that combines them" approach: it doesn't scale well.

We would need to define a way to be able to work with multiple abilities easily.
