### ISSUE TITLE
Unjoined game with "Playing" status.

### ISSUE THREAD

**Issue by kenan-rhoton** [doner-kebard/card-game-backend#27]
**Description**
A created game that has not been joined shows the Playing status instead of the "Waiting for an opponent" status

**To Reproduce**
1. `http POST :3000/lobby`
2. `http GET :3000/games/{insert game ID here}/player/{insert player ID here}`
3. The response contains an empty game with status "Playing"

**Expected behavior**
The response contains an empty game with status "Waiting for an opponent"

**Additional context**
We should return a "Waiting for an opponent" status until another player has joined the game.

**Comment by Masclins** [comment]
Apparently "Resvoles #27" it's not clear enough for github
