### ISSUE TITLE
Use HTTP Status Codes Consistently

### ISSUE THREAD

**Issue by kenan-rhoton** [doner-kebard/card-game-backend#4]
**Description of the current situation**
Currently, the api returns to the frontend a game state where there is a `:status`. The current *status* is only used by the frontend to decide what to show, but can be known using only completely public information.

Also, at `configurations/configuration.yml` and the files that use that we are treating the same way the messages used to describe the statuses and errors.

And (probably the most notorious thing) we are always returning code 200, even when we return an error message.

**Description of what I'd like**
A clear documentation on how we use HTTP statuses and create a wrapper function that assigns it with the appropiate code and message. An important part would be returning code 4xx when we are also returning an error message.

That would imply modifying the `configurations/configuration.yml` so it intuitively shows which are error messages and which aren't

**Describe alternatives you've considered**
I've thought about simply dividing the `configuration.yml` file in statuses and errors, but that doesn't makes thinks clearer, since we are always returning a status code 200.

Also, I created this Issue suggesting to remove the `:status` from backend, but apparently that wouldn't be compliant with HTTP status codes.

**Notes**
I labeled it as minor, but if we begin to use this status for more things (probably for weird or lazy reasons) it'll be more difficult to change.

**Comment by kenan-rhoton** [comment]
The inconsistent use of `:status`is making it very difficult to parse the response from a frontend perspective. We should 100% split the concept of `:status` and `:game-status` into two different things, instead of reusing it all around.

**Comment by kenan-rhoton** [comment]
It's especially problematic since `:status` is an Integer and `:game-status` would be a String.

**Comment by Masclins** [comment]
As I understand it, all current `:status` should be `:game-status` and then `:status` would be derived from either having an `:error` or not.
Is that true?

**Comment by kenan-rhoton** [comment]
Mostly. I think the response should take the followig forms:

**Lobby**
```clojure
{
  :headers {}
  :status 200
  :body {:game-id 2 :player-id "01234567-89ab-cdef-fedc-ba8976543210" :game-status "Waiting for an opponent" }
}
```

**Game**
```clojure
{
  :headers {}
  :status 200
  :body {
        :game-id 2
        :player-id "01234567-89ab-cdef-fedc-ba8976543210"
        :game-status "Playing"
        :cards [...]
  }
}
```

If we have all the game-state inside the `body` we will *never* have conflicts with HTTP Standard definitions.

Aside from that, the external status (and I recommend renaming the internal `:status` to `:game-status` so it's less ambiguous to talk about), should generally be a 200 except for two very important cases:

1. 40x when the request contains an error (like the 404 when looking for a page that doesn't exist)
2. 50x when we have recovered from an unexpected error within our code (like an exception)

Other more fine-grained definitions will come up once the backend is fully fixed and we can create a first frontend and generate a contract from it.

**Comment by Masclins** [comment]
What are `:headers`? Should we always return `{}` (for now)?

**Comment by kenan-rhoton** [comment]
The headers contains any headers we want to specify (for example our `responsify` function adds come Cross-Origin Resource Sharing headers or CORS to allow GET and POST requests from any IP)

I don't think we really want to add any others, aside from those which indicate to browsers that it's ok to send us any kind of Request)

**Comment by Masclins** [comment]
If I understood correctly...

When we are returning a game-state, response should be as it is now:
```
{
  :headers {}
  :status 200
  :body {...}
}
```

When the game-state is really an error, response should be...
```
{
  :headers {}
  :status 400
  :body {:error error-message}
}
```

In the case we have a not expected error (which would be found through try/catch, I guess), we should return:
```
{
  :headers {}
  :status 500
}
```


Is that correct?

**Comment by kenan-rhoton** [comment]
That is correct. Also, any instance which generates the third kind of error (and a 500 code) should be filed as a bug to be fixed
