### ISSUE TITLE
Exceptions should never reach the client

### ISSUE THREAD

**Issue by kenan-rhoton** [doner-kebard/card-game-backend#9]
**Description**
When encountering exceptions such as produced by #8, the client receives all of the exception data. This should never happen, we should hide any exceptions from the client and instead log them while returning an error code of the 50x class (Internal Server Error)

**To Reproduce**
See #8 

**Expected behavior**
A normal JSON response with `:status 50x`

**Additional context**
This is related to #4, but due to the added layer of catching server exceptions it's a separate issue.

**Comment by Masclins** [comment]
In this case should we return no `:body`?
